name: Build iOS IPA

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Select Xcode
        run: sudo xcode-select -switch /Applications/Xcode.app/Contents/Developer

      - name: Install CocoaPods
        run: |
          cd SRC
          pod install || pod install --repo-update

      - name: Build Xcode Project
        run: |
          cd SRC
          # Arbeitsbereich und Schema dynamisch finden
          WORKSPACE=$(ls -d *.xcworkspace | head -n 1)
          SCHEME=$(xcodebuild -workspace "$WORKSPACE" -list | grep -A 10 "Schemes:" | tail -n +2 | xed -e 's/^[ \t]*//' | head -n 1 | xargs)
          
          if [ -z "$SCHEME" ]; then
            SCHEME="Navi für ninebot"
          fi
          
          echo "Verwende Workspace: $WORKSPACE"
          echo "Verwende Scheme: $SCHEME"

          xcodebuild -workspace "$WORKSPACE" -scheme "$SCHEME" -configuration Release -sdk iphoneos -derivedDataPath build CODE_SIGNING_ALLOWED=NO CODE_SIGNING_REQUIRED=NO

      - name: Zip Payload to IPA
        run: |
          cd SRC
          mkdir -p build/Payload
          cp -r build/Build/Products/Release-iphoneos/*.app build/Payload/
          cd build
          zip -r SegwayWorld.ipa Payload

      - name: Upload IPA Artifact
        uses: actions/upload-artifact@v4
        with:
          name: SegwayWorld-IPA
          path: SRC/build/SegwayWorld.ipa
